### ISSUE TITLE
Can't share uploaded file with expiration shared link

### ISSUE THREAD

**Issue by Tezei** [tomgross/pcloud#73]
Hiya!
Congrats about awesome package that you made. Can I ask you how to share uploaded file and get temporary shared link with expiration?

Thanks in advanced!

**Comment by ikwyl6** [comment]
Seems like you can only share a folder from the pcloud api: https://docs.pcloud.com/methods/sharing/
This hasn't been implemented yet in pycloud api: https://github.com/tomgross/pycloud/blob/master/src/pcloud/api.py#L442

**Comment by tomgross** [comment]
Unfortunately generating a public link is restricted.

_This method can't be used from web applications. Referrer is restricted to pcloud.com._  (see
https://docs.pcloud.com/methods/public_links/getfilepublink.html)

**Comment by tomgross** [comment]
New version 1.2 of pcloud released on pypi: https://pypi.org/project/pcloud/

**Comment by ikwyl6** [comment]
Strange that public link for file is restricted but folder is not (or doesn't say it atleast): https://docs.pcloud.com/methods/public_links/getfolderpublink.html
